packageExtensions:
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/core": "*"
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
